services:
  database:
    container_name: devpro_database
    image: postgres:16
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=flypro       # Default user
      - POSTGRES_PASSWORD=flypro   # Password for the default user
      - POSTGRES_DB=devpro        # Database to be created automatically
    ports:
      - 5434:5432
