# fly.toml app configuration file generated for devpro-django on 2024-12-06T23:25:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devpro-django'
primary_region = 'gig'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/code/public"
  url_prefix = "/static"
