on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Devpro Integration Continuous
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://devpro:devpro@localhost:5432/flypro

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: devpro
          POSTGRES_USER: devpro
          POSTGRES_DB: flypro

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.7'
        cache: pip
    - name: Copying configurations
      run: |
        cp contrib/env-sample .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Flake8
      run: flake8 .
    - name: Test with pytest
      run: |
        pytest pypro --cov=pypro
