on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Devpro Integration Continuous
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://devpro:devpro@localhost:5432/flypro

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: devpro
          POSTGRES_USER: devpro
          POSTGRES_DB: flypro
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.7'
    - name: Copying configurations
      run: |
        cp contrib/env-sample .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Flake8
      run: flake8 .
    - name: Test with pytest
      run: |
        pytest pypro --cov=pypro
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
