# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

on:
  workflow_run:
    workflows:
      - Devpro Integration Continuous
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Devpro Deploy
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
    environment:
      name: production
      url: https://devpro-django.fly.dev
